
create table KHACHHANG
(
	SDT_KHACHHANG INT PRIMARY KEY ,
	id_KHACHHANG VARCHAR(25) NOT NULL,
	pass_KHACHHANG VARCHAR(25) NOT NULL,
	HOTEN_KHACHHANG NVARCHAR(30) NOT NULL DEFAULT N'CHƯA CÓ TÊN',
	NAMSINH_KHACHHANG DATETIME NOT NULL DEFAULT N'CHƯA NHẬP TUỔI',
	CMND_KHACHHANG INT NOT NULL DEFAULT N'CHƯA CÓ CMND',
	DIACHI_KHACHHANG NVARCHAR(30) NOT NULL DEFAULT N'CHƯA CÓ ĐỊA CHỈ'


)

create table CHUTRO
(
	SDT_CHUTRO INT PRIMARY KEY ,
	id_CHUTRO VARCHAR(25) NOT NULL,
	pass_CHUTRO VARCHAR(25) NOT NULL,
	HOTEN_CHUTRO NVARCHAR(30) NOT NULL DEFAULT N'CHƯA CÓ TÊN',
	NAMSINH_CHUTRO DATETIME NOT NULL DEFAULT N'CHƯA NHẬP TUỔI',
	CMND_CHUTRO INT NOT NULL DEFAULT N'CHƯA CÓ CMND',
	DIACHICHUTRO NVARCHAR(30) NOT NULL DEFAULT N'CHƯA CÓ ĐỊA CHỈ',
	DANGCOTAIKHOAN BIT NULL

)

create table DANGNHAP
(	
	id_taikhoan int IDENTITY(1,1) PRIMARY KEY,
	SDT_KHACHHANG int FOREIGN KEY REFERENCES KHACHHANG(SDT_KHACHHANG),
	SDT_CHUTRO int FOREIGN KEY REFERENCES CHUTRO(SDT_CHUTRO),
)


create table ChiTietHopDong
(
	id_HOPDONG INT PRIMARY KEY , 
	id_PHONGTRO int NOT NULL,
	tienDatCoc int NOT NULL,
	thoiGianDatCoc DATETIME NOT NULL,
	NgayLapHopDong DATETIME NOT NULL DEFAULT N'THIẾU NGÀY LẬP HỢP ĐỒNG',
	NgayKetThucHopDong DATETIME NOT NULL DEFAULT N'THIẾU NGÀY KẾT THÚC HỢP ĐỒNG',
	ghichu NVARCHAR(50) NULL
)
create table TrangThietBi
(
	id_TTTB int primary key,
	id_PHONGTRO INT NOT NULL, 
	TenThietBi NVARCHAR(25) NOT NULL,
	GIATHIETBI int NOT NULL DEFAULT N'THIẾU GIÁ RỒI NHÁ',
	tinhTrangThietBi BIT NOT NULL, 
	ghiChuTTTB NVARCHAR(50) NULL
)
create table LoaiPhong
(
	id_LOAIPHONG int primary key,
	id_PHONGTRO int NOT NULL, 
	TenLOAIPHONG NVARCHAR(25) NOT NULL DEFAULT N'THIẾU TÊN PHÒNG',
	GIAPHONG int NOT NULL DEFAULT N'THIẾU GIÁ RỒI NHÁ',
	soLuongNguoi int NOT NULL,
	tinhTrangPhong BIT NOT NULL, 
	ghichuLoaiPHONG NVARCHAR(50) NULL
)

create table PHONGTRO
(
	id_PHONGTRO int primary key , 
	id_HOPDONG int  FOREIGN KEY REFERENCES ChiTietHopDong(id_HOPDONG),
	id_TTTB int  FOREIGN KEY REFERENCES TrangThietBi(id_TTTB),
	id_LOAIPHONG int  FOREIGN KEY REFERENCES LoaiPhong(id_LOAIPHONG),
	SDT_CHUTRO int FOREIGN KEY REFERENCES CHUTRO(SDT_CHUTRO),
	giaTien int NOT NULL, 
	ghichuPhong NVARCHAR(50) NULL
)
create table HOPDONG
(
	ma_HOPDONG INT PRIMARY KEY , 
	SDT_KHACHHANG int FOREIGN KEY REFERENCES KHACHHANG(SDT_KHACHHANG),
	SDT_CHUTRO int FOREIGN KEY REFERENCES CHUTRO(SDT_CHUTRO),
	id_HOPDONG int FOREIGN KEY REFERENCES ChiTietHopDong(id_HOPDONG),
	TINHTRANG BIT NOT NULL DEFAULT N'KHÔNG THỂ QUÊN CHỌN',
	ghichu NVARCHAR NULL
)

create table DANGBAIKIEMTRO_KHACHHANG
(
	id_BAIVIETKHACHHANG int primary key,
	SDT_KHACHHANG int FOREIGN KEY REFERENCES KHACHHANG(SDT_KHACHHANG),
	tieuDe_KH NVARCHAR(25) NOT NULL DEFAULT N'Khong được thiếu tiêu đề nhé',
	tenBaiViet_KH NVARCHAR(25) NOT NULL DEFAULT N'Khong được thiếu TÊN BÀI VIẾT',
	noiDung_KH NVARCHAR(255) NOT NULL DEFAULT N'PHẢI CÓ NỘI DUNG',
	thoigianDangBai_KH DATETIME NOT NULL,
	thoigianKetThuc_KH DATETIME NOT NULL,
	tinhtrangBai_KH BIT NOT NULL	
)

create table DANGBAI_CHUTRO
(
	id_BAIVIETCHUTRO int primary key,
	SDT_CHUTRO int FOREIGN KEY REFERENCES CHUTRO(SDT_CHUTRO),
	tieuDe_CT NVARCHAR(25) NOT NULL DEFAULT N'Khong được thiếu tiêu đề nhé',
	tenBaiViet_CT NVARCHAR(25) NOT NULL DEFAULT N'Khong được thiếu TÊN BÀI VIẾT',
	noiDung_CT NVARCHAR(255) NOT NULL DEFAULT N'PHẢI CÓ NỘI DUNG',
	thoigianDangBai_CT DATETIME NOT NULL,
	thoigianKetThuc_CT DATETIME NOT NULL,
	tinhtrangBai_KH BIT NOT NULL
)

create table DANGBAI
(
	id_BAIVIET int primary key,
	id_BAIVIETKHACHHANG int  FOREIGN KEY REFERENCES DANGBAIKIEMTRO_KHACHHANG(id_BAIVIETKHACHHANG),
	id_BAIVIETCHUTRO int  FOREIGN KEY REFERENCES DANGBAI_CHUTRO(id_BAIVIETCHUTRO),
	thoigianDangBai DATETIME NOT NULL,
	ghichuBAIDANG NVARCHAR(25) NULL
)