
create table KHACHHANG
(
	idKHACHHANG int(20) PRIMARY KEY ,
	id_KHACHHANG VARCHAR(25) NOT NULL,
	pass_KHACHHANG VARCHAR(25) NOT NULL,
	HOTEN_KHACHHANG VARCHAR(30) NOT NULL ,
	NAMSINH_KHACHHANG DATETIME NOT NULL ,
	CMND_KHACHHANG int(20) NOT NULL,
	SDT_KHACHHANG int(20)NOT NULL,
	DIACHI_KHACHHANG VARCHAR(30) NOT NULL 


)

create  table CHUTRO
(
	idCHUTRO int(20) PRIMARY KEY ,
	id_CHUTRO VARCHAR(25) NOT NULL,
	pass_CHUTRO VARCHAR(25) NOT NULL,
	HOTEN_CHUTRO VARCHAR(30) NOT NULL ,
	NAMSINH_CHUTRO DATETIME NOT NULL ,
	CMND_CHUTRO int(20)NOT NULL ,
	SDT_CHUTRO int(20) NOT NULL,
	DIACHICHUTRO VARCHAR(30) NOT NULL ,
	DANGCOTAIKHOAN BIT NULL

)

create table DANGNHAP
(	
	id_taikhoan int(20) IDENTITY(1,1) PRIMARY KEY,
	idKHACHHANG int(20) FOREIGN KEY REFERENCES KHACHHANG(idKHACHHANG),
	idCHUTRO int(20) FOREIGN KEY REFERENCES CHUTRO(idCHUTRO),
)


create table ChiTietHopDong
(
	id_HOPDONG int(20) PRIMARY KEY , 
	id_PHONGTRO int(20) NOT NULL,
	tienDatCoc int(20) NOT NULL,
	thoiGianDatCoc DATETIME NOT NULL,
	NgayLapHopDong DATETIME NOT NULL ,
	NgayKetThucHopDong DATETIME NOT NULL ,
	ghichu VARCHAR(50) NULL
)
create table TrangThietBi
(
	id_TTTB int(20) primary key,
	id_PHONGTRO int(20) NOT NULL, 
	TenThietBi VARCHAR(25) NOT NULL,
	GIATHIETBI int(20) NOT NULL,
	tinhTrangThietBi BIT NOT NULL, 
	ghiChuTTTB VARCHAR(50) NULL
)
create table LoaiPhong
(
	id_LOAIPHONG int(20) primary key,
	id_PHONGTRO int(20) NOT NULL, 
	TenLOAIPHONG VARCHAR(25) NOT NULL ,
	GIAPHONG int(20) NOT NULL ,
	soLuongNguoi int(20) NOT NULL,
	tinhTrangPhong BIT NOT NULL, 
	ghichuLoaiPHONG VARCHAR(50) NULL
)

create table PHONGTRO
(
	id_PHONGTRO int(20) primary key , 
	id_HOPDONG int(20)  FOREIGN KEY REFERENCES ChiTietHopDong(id_HOPDONG),
	id_TTTB int(20)  FOREIGN KEY REFERENCES TrangThietBi(id_TTTB),
	id_LOAIPHONG int(20)  FOREIGN KEY REFERENCES LoaiPhong(id_LOAIPHONG),
	idCHUTRO int(20) FOREIGN KEY REFERENCES CHUTRO(idCHUTRO),
	giaTien int(20) NOT NULL, 
	ghichuPhong VARCHAR(50) NULL
)
alter table <table cần thêm>add constraint <tên khóa ngoại> 
foreign key (<cột của table hiện tại>) references <tên table cần liên kết>(<tên cột cần liên kết>)
create table HOPDONG
(
	ma_HOPDONG int(20) PRIMARY KEY , 
	idKHACHHANG int(20) FOREIGN KEY REFERENCES KHACHHANG(idKHACHHANG),
	idCHUTRO int(20) FOREIGN KEY REFERENCES CHUTRO(idCHUTRO),
	id_HOPDONG int(20) FOREIGN KEY REFERENCES ChiTietHopDong(id_HOPDONG),
	TINHTRANG BIT NOT NULL ,
	ghichu VARCHAR NULL
)

create table DANGBAIKIEMTRO_KHACHHANG
(
	id_BAIVIETKHACHHANG int(20) primary key,
	idKHACHHANG int(20) FOREIGN KEY REFERENCES KHACHHANG(idKHACHHANG),
	tieuDe_KH VARCHAR(25) NOT NULL ,
	tenBaiViet_KH VARCHAR(25) NOT NULL ,
	noiDung_KH VARCHAR(255) NOT NULL DEFAULT,
	thoigianDangBai_KH DATETIME NOT NULL,
	thoigianKetThuc_KH DATETIME NOT NULL,
	tinhtrangBai_KH BIT NOT NULL	
)

create table DANGBAI_CHUTRO
(
	id_BAIVIETCHUTRO int(20) primary key,
	idCHUTRO int(20) FOREIGN KEY REFERENCES CHUTRO(idCHUTRO),
	tieuDe_CT VARCHAR(25) NOT NULL DEFAULT ,
	tenBaiViet_CT VARCHAR(25) NOT NULL DEFAULT ,
	noiDung_CT VARCHAR(255) NOT NULL DEFAULT,
	thoigianDangBai_CT DATETIME NOT NULL,
	thoigianKetThuc_CT DATETIME NOT NULL,
	tinhtrangBai_KH BIT NOT NULL
)

create table DANGBAI
(
	id_BAIVIET int(20) primary key,
	id_BAIVIETKHACHHANG int(20) FOREIGN KEY REFERENCES KHACHHANG(idKHACHHANG),
	id_BAIVIETCHUTRO int(20) FOREIGN KEY REFERENCES CHUTRO(idCHUTRO),
idKHACHHANG int(20) FOREIGN KEY REFERENCES KHACHHANG(idKHACHHANG),
	idCHUTRO int(20) FOREIGN KEY REFERENCES CHUTRO(idCHUTRO),
	thoigianDangBai DATETIME NOT NULL,
	ghichuBAIDANG VARCHAR(25) NULL
)